### PR TITLE
Issue 27 - generate errors when templates are incorrect

### LINKED ISSUE #27: Don't silently fail if template doesn't compile
If your template isn't correct it will silently fail and not output the errors

### PR DESCRIPTION
**Pull request by michaelcd**
Closes #27 

Add callback to writeTemplate, so that errors are generated when writeTemplate fails.

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -214,6 +214,39 @@ test.cb('accepts template object and generates html', (t) => {
...
+        path: '../template/error.html',
+        output: (item) => `posts/${item.title}.html`
+      }
+    }]
+  })
+
+  const projectPath = path.join(__dirname, 'fixtures/default')
+  const project = new Spike({
+    root: projectPath,
+    posthtml: { defaults: [exp({ locals })] },
```
Comment (jescalan) [inline test/index.js]: this needs to be `plugins` to work with the latest version of spike

Comment (michaelcd) [inline test/index.js]: True. `spike-rooftop` is still using 0.8.0 of `spike-core` though, so this will continue to work until that dependency is updated.

Comment (jescalan) [inline test/index.js]: Should we run that update in a new PR? Probably a good idea to get it working with the latest spike release 😁

Comment (michaelcd) [inline test/index.js]: Yea I think a new PR would be best. I saw #25 is already up, I wasn't sure when that would go in.

Comment (jescalan) [inline test/index.js]: 👍

Comment (jescalan) [inline test/index.js]: Actually I think I'll merge that now, since tests are passing. Could you rebase on top of this and patch, then we have everything ready for release?

Comment (michaelcd) [inline test/index.js]: Sure, sounds good. Will rebase once it's merged.

**Comment by michaelcd** [comment]
Rebased for the spike-core update.

**Comment by hhsnopek** [comment]
🎉🎉🎉🎉🎉
